server: 
  port: 8888

spring: 
  cloud: 
    config: 
      server:
        git: 
          uri: https://github.com/GustavoLira-ChE/todo-list-microservices/tree/config-server/todo-backend-microservices/config-data
  application:
    name: config-server