server: 
  port: 8888

spring: 
  cloud: 
    config: 
      server:
        label: config-server
        git: 
          default-label: config-server
          uri: https://github.com/GustavoLira-ChE/config-file
  application:
    name: config-server