server: 
  port: 8888

spring: 
  cloud: 
    config: 
      server:
        git: 
          uri: file://wsl.localhost/Ubuntu-20.04/home/gustavolira/tcsTraining/cs4-react-spring-microservices/todo-backend-microservices/config-data
  application:
    name: config-server