server: 
  port: 8888

spring: 
  cloud: 
    config: 
      server:
        git: 
          uri: https://github.com/GustavoLira-ChE/config-file
          skip-ssl-validation: true
          label: config-server
  application:
    name: config-server